FROM quay.io/centos/centos:7

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

RUN yum install -y epel-release && \
    yum install -y python34 python36 && \
    yum clean all && \
    pip3 install --upgrade pip && \
    pip3 install tox

COPY . /package
WORKDIR /package

CMD [ "tox" ]
